//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBookERDiagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddressBookServiceEntities : DbContext
    {
        public AddressBookServiceEntities()
            : base("name=AddressBookServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressBook> AddressBooks { get; set; }
        public virtual DbSet<AddressBookName> AddressBookNames { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
    }
}
